export const StyleConfig = {
    control: (provided, state) => ({
        ...provided,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'flex-start',
        gap: 4,
        border: 'none',
        height: 32,
        width: '100%',
        background: '#fff',
        padding: 0,
    }),
    indicatorsContainer: (provided, state) => ({
        ...provided,
        background: state.selectProps.menuIsOpen ? '#bfbfbf' : '#F2F2F2',
        height: '100%',
        borderRadius: 4,
        padding: '0  .45rem',
    }),
    valueContainer: (provided, state) => ({
        ...provided,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: '#F2F2F2',
        height: '100%',
        width: 150,
        padding: 0,
        borderRadius: 4,
        paddingRight: 5,
    }),
    option: (provided, state) => ({
        ...provided,
        backgroundColor: state.isFocused ? '#F2F9FF' : '#fff',
        fontWeight: state.isSelected ? '500' : '400',
        fontSize: '0.85rem',
    }),
    singleValue: (provided, state) => ({
        ...provided,
        fontSize: '0.8rem',
        fontWeight: 500,
    }),
};
