<?php

namespace Give\Tests\Unit\FormMigration;

use Give\Tests\TestCase;
use Give\Tests\TestTraits\RefreshDatabase;

class FunctionsTest extends TestCase
{
    use RefreshDatabase;

    protected $redirectedFormIdLookup = [
        1 => 101,
        2 => 202,
        3 => 303,
    ];

    protected $transferredFormIdLookup = [
        1 => 101,
    ];

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        global $wpdb;

        foreach($this->redirectedFormIdLookup as $oldId => $newId) {
            $wpdb->insert($wpdb->prefix . 'give_formmeta', [
                'form_id' => $newId,
                'meta_key' => 'redirectedFormId',
                'meta_value' => $oldId,
            ]);
        }

        foreach($this->transferredFormIdLookup as $oldId => $newId) {
            $wpdb->insert($wpdb->prefix . 'give_formmeta', [
                'form_id' => $newId,
                'meta_key' => 'transferredFormId',
                'meta_value' => $oldId,
            ]);
        }
    }

    public function testSingleValueUpdate()
    {
        $formId = 2;

        give_redirect_form_id($formId);

        $this->assertEquals($formId, $this->redirectedFormIdLookup[2]);
    }

    public function testMultipleValueUpdate()
    {
        $formId = 2;
        $atts['id'] = 2;

        give_redirect_form_id($formId, $atts['id']);

        $this->assertEquals($formId, $this->redirectedFormIdLookup[2]);
        $this->assertEquals($atts['id'], $this->redirectedFormIdLookup[2]);
    }

    public function testArrayValueUpdate()
    {
        $ids = [
            1 => 1,
            2 => 2,
        ];

        give_redirect_form_id($ids);

        $this->assertEquals($ids[1], $this->redirectedFormIdLookup[1]);
        $this->assertEquals($ids[2], $this->redirectedFormIdLookup[2]);
    }

    public function testIsFormMigrated()
    {
        $this->assertTrue(give_is_form_migrated(1));
        $this->assertFalse(give_is_form_migrated(4));
    }

    public function testIsFormDonationsTransferred()
    {
        $this->assertTrue(give_is_form_donations_transferred(1));
        $this->assertFalse(give_is_form_donations_transferred(2));
    }
}
