export default function data() {
    return {
        id: 3690,
        form: {
            id: 1,
            name: 'Campers international test test long text test',
        },
        purchaseKey: '51efe4fe390f8af8a72801e74025cdf2',
        createdAt: '2023-03-09 13:36:20',
        updatedAt: '2023-03-09 13:36:20',
        status: 'revoked',
        type: 'renewal',
        mode: 'test',
        amount: '$25.00',
        feeAmountRecovered: '$1.46',
        gatewayId: 'paypal',
        gateway: 'Paypal Gateway',
        donorId: 8,
        firstName: 'Jonathan',
        lastName: 'Waldstein',
        email: 'jpwaldstein@gmail.com',
        subscriptionId: 147,
        billingAddress: {
            country: null,
            address1: null,
            address2: null,
            city: null,
            state: null,
            zip: null,
        },
        anonymous: false,
        gatewayTransactionId: 'test-gateway-transaction-id-3690',
        company: null,
    };
}
