import PaypalIcon from '@givewp/components/AdminUI/Icons/PaypalIcon';

export const paymentMethodList = {
    manual: null,
    offline: null,
    paypalpro_payflow: null,
    paypalpro: <PaypalIcon />,
    paypalpro_rest: null,
    paymill: null,
    stripe: null,
    stripe_checkout: null,
    stripe_sepa: null,
    stripe_becs: null,
    paypal: null,
    'paypal-commerce': null,
    authorize: null,
    authorize_echeck: null,
    payfast: null,
    square: null,
    stripe_ach: null,
    stripe_apple_pay: null,
    stripe_google_pay: null,
    stripe_ideal: null,
    bitpay: null,
    twocheckout: null,
    braintree: null,
    ccavenue: null,
    iats: null,
    mollie: null,
    moneris: null,
    paytm: null,
    payumoney: null,
    americloudpayments: null,
    americloudpayments_ach: null,
    razorpay: null,
    sofort: null,
};
