import PaypalIcon from '@givewp/components/AdminUI/Icons/PaypalIcon';

export const paymentMethodList = {
    manual: '',
    offline: '',
    paypalpro_payflow: <PaypalIcon />,
    paypalpro: <PaypalIcon />,
    paypalpro_rest: <PaypalIcon />,
    paymill: '',
    stripe: '',
    stripe_checkout: '',
    stripe_sepa: '',
    stripe_becs: '',
    paypal: '',
    'paypal-commerce': '',
    authorize: '',
    authorize_echeck: '',
    payfast: '',
    square: '',
    stripe_ach: '',
    stripe_apple_pay: '',
    stripe_google_pay: '',
    stripe_ideal: '',
    bitpay: '',
    twocheckout: '',
    braintree: '',
    ccavenue: '',
    iats: '',
    mollie: '',
    moneris: '',
    paytm: '',
    payumoney: '',
    americloudpayments: '',
    americloudpayments_ach: '',
    razorpay: '',
    sofort: '',
};
