name: 'Close stale issues'
on:
    schedule:
        - cron: '30 1 * * *' # at 1:30am every day

jobs:
    stale:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/stale@v5
              with:
                  stale-issue-message: 'This issue is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 14 additional days.'
                  stale-pr-message: 'This PR is stale because it has been open 45 days with no activity. Stale PRs will NOT be automatically closed.'
                  close-issue-message: 'This issue was closed because it has been stalled for an additional 14 days with no activity.'
                  days-before-issue-stale: 45 # ~6 weeks accounts for cycle length
                  days-before-pr-stale: 45 # ~6 weeks accounts for cycle length
                  days-before-issue-close: 14 # 2 weeks accounts for cool-down
                  days-before-pr-close: -1 # Never close pull requests
                  debug-only: true # Dry-run. No GitHub API calls that can alter your issues and pull requests will happen.
