name: 'Close stale issues'

on:
    schedule:
        -   cron: '30 1 * * *' # at 1:30am every day

jobs:
    stale:
        uses: impress-org/givewp-github-actions/.github/workflows/close-stale-issues.yml@master
