name: Plugin asset/readme updates to WordPress.org
on:
    workflow_dispatch:

jobs:
    trunk:
        name: Push to trunk
        runs-on: ubuntu-latest
        environment: live
        steps:
            -   uses: actions/checkout@master
            -   name: WordPress.org plugin asset/readme update
                uses: 10up/action-wordpress-plugin-asset-update@stable
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SLUG: give
                    IGNORE_OTHER_FILES: true
